# This pipeline creates the AP pools

name: "Refill AP Pool - Auto Triggered"

on:
  workflow_dispatch:
    inputs:
      gitRef:
        description: "Commit Id from where the pools should be created"
        required: false
        default: "master"
  schedule:
    - cron: "15 0 * * *"
    - cron: "30 13 * * *"

#Set the environment variables for tracking metrics
#env:
  #SFPOWERSCRIPTS_NEWRELIC: "true"
  #SFPOWERSCRIPTS_NEWRELIC_API_KEY: "${{ secrets.NEWRELIC_INSIGHT_INSERT_KEYS }}"

jobs:
  pool:
    name: "Refilling AP Pool with fresh scratch orgs"
    runs-on: ubuntu-latest
    container: ghcr.io/dxatscale/sfpowerscripts:22.5.5-5408150885
    timeout-minutes: 720 #Set to Maximum Time out
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.gitRef }}
          fetch-depth: 0

      - name: "Authenticate to Dev Hub"
        run: |
          echo "${{ secrets.ARCHPREPSECRET }}" > ./authfile
          sf org login sfdx-url  -f authfile -a devhub

      # Authenticate to npm
      - uses: actions/setup-node@v3
        with:
          registry-url: "https://npm.pkg.github.com"

      - name: "Prepare a pool of dev scratch orgs"
        run: "sfp orchestrator:prepare -f config/pool-configs/dev-pool-def.json -v devhub"
        env:
          NODE_AUTH_TOKEN:
            ${{ secrets.GITHUB_TOKEN }}

            # Publish artifacts
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: scratchorg-logs-pool-dev
          path: .sfpowerscripts/prepare_logs